[markdown.highlighting]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "solarized-dark", filename = "syntax-theme-dark.css" },
  { theme = "solarized-light", filename = "syntax-theme-light.css" },
]
